# Site settings
title: Pixelated Gears
email: pixelated.gears@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Pixelated Gears is a small game development studio from La Plata, Buenos Aires, Argentina.
 In this blog you will find some of our work, as well as tutorials and videos about game development and stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fede0d.github.io" # the base hostname & protocol for your site
twitter_username: fede0d
github_username:  fede0d

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

array: []
