# Site settings
title: Pixelated Gears
email: pixelated.gears@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Hello I'm Federico Pacheco and I'm a game designer from Buenos Aires, Argentina.
 I have other interests too, but what I love the most is making games.
 In this blog you will find some of my work, as well as tutorials and videos about game development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fede0d.github.io" # the base hostname & protocol for your site
twitter_username: fede0d
github_username:  fede0d

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

array: []
